theme: jekyll-theme-minimal
title: Yuvaraj Govindarajulu
description: Personal profile and blog
logo: [Location of the logo]
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
